= Compiler et construire ses applications avec maven
Guibert Rémy <guibert.remy@etu.univ-tlse2.fr>
v1, 2022-02-27 : Initial draft
:icons: font
:diagrams: .
:experimental:
:classroom-link: https://classroom.github.com/a/gWXnQmIT
:imagesdir: images

// Useful definitions
:eclipse: http://www.eclipse.org[Eclipse]
:intellij: https://www.jetbrains.com/idea/[IntelliJ]
:maven: http://maven.apache.org/[Maven]
:vscode: https://code.visualstudio.com/[VS Code]
:java: https://www.java.com/fr/download/[Java]

// Specific to GitHub
ifdef::env-github[]
:toc:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:icongit: Git
endif::[]

//---------------------------------------------------------------

WARNING: ce projet nécessite {maven} et {java} 8.
Vueillez à les installer avant d'essayer quoi que ce soit.

== Cloner

Télécharger un zip ou clonez ce dépôt et ouvrez un terminal dans le dossier du projet.

== Compilation

Pour la compiler le projet tapez `mvn clean compile package`, cela nettoyera tout les builds précédent, compilera le projet et créera un exécutable Java. Les fichiers `.class` se trouvent dans `target/classes/`, le jar est dans `target/`.

== Générer la documentation

Pour générer la documentation tapez `mvn javadoc:javadoc`. L'index de la javadoc se trouve dans `target/site/`.

== Exécution

Pour exécuter le jar tapez `java -jar target/tp_qualite-1.0.jar` dans votre terminal.

== Raccourcis

Vous pouvez utilisez les fichiers build et run pour vous faciliter la tâche.

`build.bat` s'occupe de nettoyer, compiler, packager et générer la javadoc

`run.bat` s'occupe de lancer l'exécutable Java.
